### ISSUE TITLE
Create DUNS number for SSL EV

### ISSUE THREAD

**Issue by kawaguchimaeda8** [yogo1212/evtssl#2]
Please help me. How to register SSL EV? Because it requires a duns number. I do not own a company, so I also do not have a duns number for verification. Please help.

**Comment by yogo1212** [comment]
Hi :-)

I guess you are facing problems with SSL Extension Validation. This library is for the use of SSL with libevent - regardless of whether the certificate belongs to a company with a DUNS number.

If you just need a certificate that can be validated by regular internet users, I would try https://letsencrypt.org/getting-started.

Good luck :-)

**Comment by kawaguchimaeda8** [comment]
Oh, I see. So i can not make ssl ev without company? And duns number ?
